### ISSUE TITLE
Error installing 8_create_hashids_decode.sql, "cannot remove parameter defaults from existing function"

### ISSUE THREAD

**Issue by djeikyb** [array-analytics/plpg_hashids#11]
I get the same error with the all-in-one version, but I ran it as a series of `psql -f` statements just to double check which file had the problem. Ran on dockerized postgres:

> PostgreSQL 10.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit

You can see files 1-7 ran just fine, and then file 8 had a problem:

> psql:7_create_hashids_encode.sql:5: NOTICE:  function hashids.encode(pg_catalog.int8,text,pg_catalog.int4,text,pg_catalog.bool) does not exist, skipping
> DROP FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> Pager usage is off.
> psql:8_create_hashids_decode.sql:2: NOTICE:  function hashids.decode(text,text,pg_catalog.int4,text,pg_catalog.bool) does not exist, skipping
> DROP FUNCTION
> psql:8_create_hashids_decode.sql:3: NOTICE:  function hashids.decode(text,text,pg_catalog.int4,text) does not exist, skipping
> DROP FUNCTION
> psql:8_create_hashids_decode.sql:4: NOTICE:  function hashids.decode(text,text,pg_catalog.int4) does not exist, skipping
> DROP FUNCTION
> psql:8_create_hashids_decode.sql:5: NOTICE:  function hashids.decode(text,text) does not exist, skipping
> DROP FUNCTION
> psql:8_create_hashids_decode.sql:6: NOTICE:  function hashids.decode(text) does not exist, skipping
> DROP FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> CREATE FUNCTION
> psql:8_create_hashids_decode.sql:187: ERROR:  cannot remove parameter defaults from existing function
> HINT:  Use DROP FUNCTION hashids.decode(text,text,integer,text,boolean) first.

**Comment by rhux** [comment]
There was a pull request that fixes this issue. It was just merged.
